//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace foxcon.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departamentos
    {
        public Departamentos()
        {
            this.Employees = new HashSet<Employees>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string active { get; set; }
        public System.DateTime created_at { get; set; }
        public byte[] modifield_at { get; set; }
    
        public virtual ICollection<Employees> Employees { get; set; }
    }
}
